# Tmux Config File

# Colors
white="#FFFFFF"
gray_light="#D8DEE9"
gray_medium="#9BA2AF"
gray_dark="#5B6272"
mint="#92C472"

# Visual
set -g status-position top

# status line
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${white},bold] #S #[fg=${gray_dark},nobold]| "
# battery + time
set -g status-right "#(cat /sys/class/power_supply/BAT0/capacity)%%#([ $(cat /sys/class/power_supply/BAT0/status) = 'Charging' ] && echo '󱐌') | %H:%M"

# splits open in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set -g window-status-current-format "#[fg=${mint},bold]#I:#W"
set -g window-status-format "#[fg=#{gray_medium}]#I:#W"

# set command mode color
set -g message-style "fg=${white},bg=default"

# set selection mode color
set -g mode-style "fg=${white},bg=${mint},bold"

# mouse mode on to enable scrolling
set -g mouse on

# enable clipboard
set -g set-clipboard on
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# open lazygit in floating window
bind g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" lazygit

# fzf in floating window
bind-key s display-popup -w 50% -h 25% -E "tmux list-sessions -F '#S' | fzf --reverse --preview 'tmux list-windows -t {}'| xargs -r tmux switch-client -t"


