# yazi keymaps

[[mgr.prepend_keymap]]
on   = "o"
run  = "create"
desc = "Create file or directory"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = "shell -- ripdrag -xi %s"
